name: Publish Docker image
on:
  push:
    branches: [main]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: download staticman
        run: |
          git clone https://github.com/eduardoboucas/staticman
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: staticman 
          file: ./staticman/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/${{github.repository}}:master
          push: true

